### ISSUE TITLE
Not found. Authentication passthru.

### ISSUE THREAD

**Issue by FreddySerg** [u2i/omniauth-classlink#5]
I get the error "Not found error. Authentication passthru." when following a link

POST /users/auth/class_link

Gems
devise 4.8.0
oauth2 1.4.7
omniauth 2.0.4
omniauth-oauth2 1.7.1
omniauth-classlink 0.3.1
omniauth-rails_csrf_protection 1.0.0

**Comment by kamilbednarz** [comment]
Hey @FreddySerg I guess you're trying to hit the wrong route.

It should be `POST /users/auth/classlink`.

**Comment by FreddySerg** [comment]
@kamilbednarz Thank you, yes, this link works, but FYI the gem devise automatically generates a link to 
`/users/auth/class_link`
So the settings described in Readme.md will not work.

**Comment by glebe** [comment]
@FreddySerg you can add 'name' attribute to the configuration section to fix it, because name is defined as "classlink" inside the strategy file itself:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :class_link,
           Rails.application.secrets.classlink_client_id,
           Rails.application.secrets.classlink_secret,
           name: 'class_link',
           strategy_class: 'OmniAuth::Strategies::ClassLink'
end
```
